import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import type { Plugin } from "vite";

/** Offline-instalar door 2: every cache of the game starts with this; the version follows. */
export const CACHE_PREFIX = "forzion-futmanager-";

/** Offline-instalar AC 1: left out of the cache - the worker itself, the share card and the music (12 MB). */
const skipped = (path: string) => path === "sw.js" || path === "og-image.png" || path.startsWith("audio/");

/** Offline-instalar AC 1: `./` and every file of the build the game needs, as `./<path>`, sorted. */
export function precacheList(dir: string): string[] {
  const files = readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter((f) => f.isFile())
    .map((f) => relative(dir, join(f.parentPath, f.name)).split(sep).join("/"))
    .filter((path) => !skipped(path))
    .sort();
  return ["./", ...files.map((path) => `./${path}`)];
}

/** Offline-instalar AC 2: the first 12 hex digits of the SHA-256 of each listed path and its content, in order. */
export function cacheVersion(dir: string, list: readonly string[]): string {
  const hash = createHash("sha256");
  for (const entry of list) {
    if (entry === "./") continue;
    const path = entry.slice(2);
    hash.update(path).update("\0").update(readFileSync(join(dir, path))).update("\0");
  }
  return hash.digest("hex").slice(0, 12);
}

/**
 * Offline-instalar door 2: the worker. It caches the list on install, drops the game's other
 * versions on activate, and answers a navigation from the network first (the cached
 * `index.html` without it) and any other file of the site from the cache first.
 */
export function serviceWorkerSource(version: string, list: readonly string[]): string {
  return `// Generated by src/pwa/build.ts (offline-instalar, AD-027). Do not edit.
const PREFIX = ${JSON.stringify(CACHE_PREFIX)};
const CACHE = PREFIX + ${JSON.stringify(version)};
const PRECACHE = ${JSON.stringify(list)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith(PREFIX) && key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin) return;
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).catch(() =>
        caches
          .open(CACHE)
          .then((cache) => cache.match("./index.html"))
          .then((cached) => cached || Response.error()),
      ),
    );
    return;
  }
  event.respondWith(
    caches
      .open(CACHE)
      // A module script asks with an Origin header and the server may answer with Vary: Origin;
      // the cached copy was fetched without one, so Vary must not turn the hit into a miss.
      .then((cache) => cache.match(request, { ignoreVary: true }))
      .then((cached) => cached || fetch(request)),
  );
});
`;
}

/** Offline-instalar door 1: writes `sw.js` into the build output once everything else is there. */
export function serviceWorkerPlugin(): Plugin {
  let outDir = "dist";
  return {
    name: "forzion-service-worker",
    apply: "build",
    configResolved(config) {
      outDir = join(config.root, config.build.outDir);
    },
    closeBundle() {
      const list = precacheList(outDir);
      writeFileSync(join(outDir, "sw.js"), serviceWorkerSource(cacheVersion(outDir, list), list));
    },
  };
}
